In [61]:
import pandas as pd

In [62]:
messages = pd.read_csv('spam.csv', sep=',', names=["label", "message"],encoding = 'latin-1',usecols=[0,1])

In [63]:
messages

     label                                            message
0       v1                                                 v2
1      ham  Go until jurong point, crazy.. Available only ...
2      ham                      Ok lar... Joking wif u oni...
3     spam  Free entry in 2 a wkly comp to win FA Cup fina...
4      ham  U dun say so early hor... U c already then say...
...    ...                                                ...
5568  spam  This is the 2nd time we have tried 2 contact u...
5569   ham              Will Ì_ b going to esplanade fr home?
5570   ham  Pity, * was in mood for that. So...any other s...
5571   ham  The guy did some bitching but I acted like i'd...
5572   ham                         Rofl. Its true to its name

[5573 rows x 2 columns]

In [64]:
messages = messages.drop(0,)

In [65]:
messages

     label                                            message
1      ham  Go until jurong point, crazy.. Available only ...
2      ham                      Ok lar... Joking wif u oni...
3     spam  Free entry in 2 a wkly comp to win FA Cup fina...
4      ham  U dun say so early hor... U c already then say...
5      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5568  spam  This is the 2nd time we have tried 2 contact u...
5569   ham              Will Ì_ b going to esplanade fr home?
5570   ham  Pity, * was in mood for that. So...any other s...
5571   ham  The guy did some bitching but I acted like i'd...
5572   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [66]:
## DATA CLEANING and Preprocessing
import re ##regular expression library
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ACER\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [67]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

In [68]:
ps = PorterStemmer()

In [69]:
stop_words = set(stopwords.words('english'))
corpus = []
for i in range(len(messages)):
        review = re.sub('[^a-zA-Z]',' ', messages['message'].iloc[i])
        review = review.lower()
        review = review.split()
        review = [ps.stem(word) for word in review if word not in stop_words]
        review = ' '.join(review)
        corpus.append(review)

In [70]:
##Create the Bag of Words Model With N-Grams
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=2500,ngram_range=(1,2)) #this makes it a binary BOW

In [71]:
X=cv.fit_transform(corpus).toarray()
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(5572, 2500))

In [72]:
y = pd.get_dummies(messages['label'])
y=y.iloc[:,0].values

In [73]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size=0.20,random_state=42)

In [74]:
from sklearn.naive_bayes import MultinomialNB

In [75]:
model = MultinomialNB().fit(X,y)

In [76]:
y_pred = model.predict(X_test)

In [77]:
from sklearn.metrics import accuracy_score,classification_report

In [79]:
accuracy_score(y_pred,y_test)

0.9829596412556054

In [81]:
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

       False       0.92      0.95      0.94       145
        True       0.99      0.99      0.99       970

    accuracy                           0.98      1115
   macro avg       0.96      0.97      0.96      1115
weighted avg       0.98      0.98      0.98      1115