In [63]:
%pip install gensim

Requirement already satisfied: gensim in c:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages (4.4.0)
Requirement already satisfied: numpy>=1.18.5 in c:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages (from gensim) (2.4.2)
Requirement already satisfied: scipy>=1.7.0 in c:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages (from gensim) (1.17.1)
Requirement already satisfied: smart_open>=1.8.1 in c:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages (from gensim) (7.6.1)
Requirement already satisfied: wrapt in c:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages (from smart_open>=1.8.1->gensim) (2.2.1)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [64]:
import gensim
from gensim.models import Word2Vec, KeyedVectors

In [65]:
import gensim.downloader as api
wv = api.load('word2vec-google-news-300')

In [66]:
vking = wv['king']

In [67]:
vking.shape

(300,)

In [68]:
import pandas as pd 
messages = pd.read_csv('spam.csv', sep= ',', names = ['label', 'message'], encoding= 'latin-1', usecols=(0,1))

In [69]:
messages

     label                                            message
0       v1                                                 v2
1      ham  Go until jurong point, crazy.. Available only ...
2      ham                      Ok lar... Joking wif u oni...
3     spam  Free entry in 2 a wkly comp to win FA Cup fina...
4      ham  U dun say so early hor... U c already then say...
...    ...                                                ...
5568  spam  This is the 2nd time we have tried 2 contact u...
5569   ham              Will Ì_ b going to esplanade fr home?
5570   ham  Pity, * was in mood for that. So...any other s...
5571   ham  The guy did some bitching but I acted like i'd...
5572   ham                         Rofl. Its true to its name

[5573 rows x 2 columns]

In [70]:
messages = messages.drop(0,)
messages

     label                                            message
1      ham  Go until jurong point, crazy.. Available only ...
2      ham                      Ok lar... Joking wif u oni...
3     spam  Free entry in 2 a wkly comp to win FA Cup fina...
4      ham  U dun say so early hor... U c already then say...
5      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5568  spam  This is the 2nd time we have tried 2 contact u...
5569   ham              Will Ì_ b going to esplanade fr home?
5570   ham  Pity, * was in mood for that. So...any other s...
5571   ham  The guy did some bitching but I acted like i'd...
5572   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [71]:
import re

In [72]:
from nltk.stem import WordNetLemmatizer
lemma = WordNetLemmatizer()

In [73]:
corpus = []
for i in range(0, len(messages)):
    review = re.sub('[^a-zA-Z]', ' ', messages['message'].iloc[i])
    review = review.lower()
    review = review.split()

    review = [lemma.lemmatize(word) for word in review]
    review = ' '.join(review)
    corpus.append(review)

In [74]:
import nltk

In [75]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess  ##important

In [76]:
## simple_preprocess converts a document into a list of lower case tokens ignoring tokens thats are too short or too long.

In [77]:
words = []
for sent in corpus:
    sent_token = sent_tokenize(sent)
    for sent in sent_token:
           words.append(simple_preprocess(sent))

In [78]:
import gensim

In [79]:
## train word2vec from scratch
model = gensim.models.Word2Vec(words, vector_size=100)

In [80]:
## to get all the vocabulary 
model.wv.index_to_key

['you',
 'to',
 'the',
 'and',
 'it',
 'in',
 'is',
 'me',
 'my',
 'for',
 'your',
 'call',
 'of',
 'that',
 'have',
 'on',
 'now',
 'are',
 'can',
 'so',
 'but',
 'not',
 'or',
 'we',
 'do',
 'get',
 'at',
 'be',
 'if',
 'ur',
 'will',
 'with',
 'no',
 'just',
 'this',
 'gt',
 'lt',
 'how',
 'go',
 'up',
 'when',
 'ok',
 'day',
 'what',
 'free',
 'from',
 'out',
 'all',
 'know',
 'll',
 'come',
 'like',
 'time',
 'good',
 'am',
 'then',
 'got',
 'wa',
 'there',
 'he',
 'text',
 'only',
 'love',
 'want',
 'send',
 'one',
 'need',
 'txt',
 'today',
 'by',
 'going',
 'home',
 'don',
 'stop',
 'she',
 'about',
 'lor',
 'sorry',
 'see',
 'mobile',
 'still',
 'take',
 'back',
 'da',
 'reply',
 'our',
 'think',
 'tell',
 'dont',
 'week',
 'phone',
 'hi',
 'new',
 'later',
 'they',
 'any',
 'pls',
 'her',
 'please',
 'ha',
 'co',
 'msg',
 'did',
 'been',
 'min',
 'an',
 'some',
 'dear',
 'make',
 'here',
 'night',
 'who',
 'message',
 'well',
 'say',
 'where',
 're',
 'thing',
 'much',
 'claim',
 'great',
 'hope',
 'oh',
 'hey',
 'him',
 'number',
 'more',
 'too',
 'happy',
 'friend',
 'wat',
 'give',
 'work',
 'had',
 'way',
 'yes',
 'www',
 've',
 'let',
 'prize',
 'should',
 'won',
 'right',
 'tomorrow',
 'already',
 'tone',
 'after',
 'ask',
 'said',
 'doing',
 'cash',
 'win',
 'yeah',
 'amp',
 'really',
 'life',
 'im',
 'babe',
 'meet',
 'find',
 'why',
 'them',
 'very',
 'morning',
 'last',
 'service',
 'year',
 'uk',
 'thanks',
 'miss',
 'would',
 'com',
 'also',
 'nokia',
 'anything',
 'lol',
 'care',
 'every',
 'feel',
 'keep',
 'pick',
 'sure',
 'sent',
 'contact',
 'urgent',
 'over',
 'something',
 'buy',
 'again',
 'before',
 'cant',
 'wait',
 'place',
 'first',
 'help',
 'guy',
 'box',
 'went',
 'wish',
 'someone',
 'nice',
 'were',
 'next',
 'even',
 'show',
 'which',
 'his',
 'tonight',
 'soon',
 'word',
 'around',
 'off',
 'money',
 'could',
 'customer',
 'many',
 'sleep',
 'chat',
 'late',
 'per',
 'ya',
 'sm',
 'gonna',
 'wan',
 'leave',
 'always',
 'down',
 'name',
 'other',
 'gud',
 'lot',
 'pm',
 'dun',
 'told',
 'end',
 'st',
 'waiting',
 'hello',
 'girl',
 'fine',
 'month',
 'hour',
 'minute',
 'coming',
 'heart',
 'haha',
 'people',
 'special',
 'th',
 'thk',
 'person',
 'yet',
 'guaranteed',
 'smile',
 'same',
 'done',
 'getting',
 'may',
 'ppm',
 'best',
 'thought',
 'try',
 'use',
 'god',
 'offer',
 'didn',
 'holiday',
 'class',
 'stuff',
 'talk',
 'line',
 'mean',
 'man',
 'live',
 'car',
 'lunch',
 'cost',
 'start',
 'few',
 'draw',
 'job',
 'finish',
 'problem',
 'bit',
 'plan',
 'house',
 'hr',
 'better',
 'thats',
 'meeting',
 'never',
 'trying',
 'yup',
 'being',
 'having',
 'ready',
 'dat',
 'ill',
 'account',
 'long',
 'cool',
 'pobox',
 'rate',
 'mind',
 'game',
 'weekend',
 'chance',
 'enjoy',
 'real',
 'half',
 'latest',
 'world',
 'than',
 'because',
 'sir',
 'guess',
 'wk',
 'yo',
 'check',
 'play',
 'room',
 'pic',
 'voucher',
 'boy',
 'nothing',
 'wanna',
 'awarded',
 'look',
 'eat',
 'camera',
 'receive',
 'lar',
 'shit',
 'big',
 'liao',
 'another',
 'sweet',
 'into',
 'po',
 'bt',
 'landline',
 'birthday',
 'ah',
 'dinner',
 'quite',
 'ever',
 'kiss',
 'might',
 'video',
 'jus',
 'luv',
 'age',
 'land',
 'watch',
 'watching',
 'xxx',
 'question',
 'probably',
 'orange',
 'baby',
 'thanx',
 'called',
 'tv',
 'worry',
 'aight',
 'bed',
 'pa',
 'once',
 'nd',
 'speak',
 'fun',
 'early',
 'point',
 'princess',
 'bad',
 'den',
 'actually',
 'sat',
 'two',
 'shall',
 'nite',
 'forgot',
 'hear',
 'part',
 'maybe',
 'ringtone',
 'doe',
 'bus',
 'remember',
 'wont',
 'network',
 'apply',
 'office',
 'dunno',
 'shopping',
 'reach',
 'easy',
 'dream',
 'between',
 'left',
 'pay',
 'code',
 'dad',
 'wife',
 'fuck',
 'put',
 'didnt',
 'face',
 'leh',
 'evening',
 'little',
 'award',
 'hurt',
 'dis',
 'mate',
 'made',
 'true',
 'gift',
 'everything',
 'sound',
 'working',
 'those',
 'mail',
 'yr',
 'school',
 'anyway',
 'movie',
 'afternoon',
 'looking',
 'xx',
 'thank',
 'enough',
 'selected',
 'town',
 'while',
 'detail',
 'asked',
 'collect',
 'tmr',
 'missing',
 'without',
 'most',
 'pound',
 'entry',
 'xmas',
 'sexy',
 'join',
 'must',
 'price',
 'okay',
 'came',
 'since',
 'valid',
 'though',
 'wif',
 'until',
 'collection',
 'bring',
 'wot',
 'book',
 'wake',
 'important',
 'hav',
 'able',
 'til',
 'answer',
 'abt',
 'mob',
 'pain',
 'run',
 'missed',
 'wanted',
 'lesson',
 'update',
 'plus',
 'away',
 'de',
 'change',
 'plz',
 'charge',
 'decimal',
 'stay',
 'juz',
 'test',
 'haven',
 'date',
 'colour',
 'attempt',
 'dude',
 'weekly',
 'music',
 'else',
 'havent',
 'wen',
 'hair',
 'double',
 'yesterday',
 'saw',
 'till',
 'alright',
 'lei',
 'goin',
 'online',
 'bored',
 'drink',
 'friendship',
 'optout',
 'shop',
 'oso',
 'id',
 'haf',
 'top',
 'food',
 'making',
 'trip',
 'yours',
 'credit',
 'net',
 'family',
 'sch',
 'these',
 'either',
 'feeling',
 'club',
 'hot',
 'gr',
 'coz',
 'player',
 'address',
 'driving',
 'yourself',
 'delivery',
 'tried',
 'ard',
 'national',
 'sad',
 'together',
 'lose',
 'sae',
 'beautiful',
 'tot',
 'head',
 'post',
 'calling',
 'full',
 'ring',
 'wid',
 'both',
 'story',
 'si',
 'smoke',
 'believe',
 'order',
 'nt',
 'busy',
 'bonus',
 'second',
 'mom',
 'http',
 'brother',
 'await',
 'drive',
 'saying',
 'mum',
 'eve',
 'poly',
 'huh',
 'chikku',
 'row',
 'walk',
 'happen',
 'noe',
 'sleeping',
 'leaving',
 'old',
 'smiling',
 'close',
 'info',
 'set',
 'drop',
 'rite',
 'email',
 'pub',
 'simple',
 'thinking',
 'suite',
 'mths',
 'okie',
 'awesome',
 'hand',
 'parent',
 'match',
 'private',
 'cause',
 'started',
 'finished',
 'took',
 'congrats',
 'tomo',
 'doesn',
 'aft',
 'news',
 'hl',
 'auction',
 'neva',
 'mine',
 'gd',
 'reason',
 'valentine',
 'sister',
 'card',
 'unsubscribe',
 'angry',
 'wil',
 'company',
 'tc',
 'break',
 'content',
 'everyone',
 'taking',
 'statement',
 'forget',
 'tho',
 'caller',
 'final',
 'available',
 'alone',
 'loving',
 'anyone',
 'gal',
 'knw',
 'sun',
 'whatever',
 'opt',
 'dating',
 'choose',
 'found',
 'touch',
 'worth',
 'carlos',
 'bank',
 'fancy',
 'each',
 'whats',
 'open',
 'type',
 'expires',
 'search',
 'ticket',
 'lucky',
 'treat',
 'party',
 'fast',
 'sub',
 'visit',
 'kind',
 'welcome',
 'mobileupd',
 'far',
 'anytime',
 'congratulation',
 'secret',
 'gbp',
 'exam',
 'college',
 'boytoy',
 'frnd',
 'hard',
 'ltd',
 'quiz',
 'identifier',
 'uncle',
 'friday',
 'happened',
 'hit',
 'gone',
 'prob',
 'song',
 'decided',
 'saturday',
 'smth',
 'winner',
 'hows',
 'chennai',
 'least',
 'wrong',
 'lovely',
 'wonder',
 'drug',
 'sea',
 'pretty',
 'fri',
 'outside',
 'nope',
 'term',
 'fucking',
 'bout',
 'project',
 'light',
 'read',
 'tel',
 'oredi',
 'goodmorning',
 'darlin',
 'finally',
 'wit',
 'mu',
 'operator',
 'used',
 'camcorder',
 'wonderful',
 'crazy',
 'wasn',
 'support',
 'earlier',
 'snow',
 'listen',
 'savamob',
 'frm',
 'cum',
 'ten',
 'jay',
 'fone',
 'blue',
 'unlimited',
 'hold',
 'cd',
 'fr',
 'meant',
 'case',
 'mrng',
 'course',
 'log',
 'ni',
 'their',
 'hmm',
 'isn',
 'frnds',
 'whole',
 'telling',
 'seeing',
 'hungry',
 'wq',
 'sunday',
 'freemsg',
 'wkly',
 'father',
 'gas',
 'john',
 'enter',
 'luck',
 'film',
 'na',
 'understand',
 'store',
 'mayb',
 'sex',
 'paper',
 'area',
 'happiness',
 'yar',
 'un',
 'within',
 'park',
 'sk',
 'india',
 'as',
 'rock',
 'couple',
 'talking',
 'motorola',
 'moment',
 'currently',
 'ago',
 'txts',
 'reading',
 'christmas',
 'lost',
 'bslvyl',
 'die',
 'stupid',
 'single',
 'dnt',
 'side',
 'march',
 'balance',
 'mr',
 'hmmm',
 'joy',
 'tired',
 'invited',
 'felt',
 'mah',
 'computer',
 'download',
 'hee',
 'cut',
 'move',
 'etc',
 'pas',
 'almost',
 'child',
 'eh',
 'valued',
 'press',
 'difficult',
 'grin',
 'surprise',
 'information',
 'heard',
 'photo',
 'knew',
 'sort',
 'extra',
 'ugh',
 'picking',
 'eye',
 'sell',
 'xy',
 'darren',
 'kid',
 'gym',
 'through',
 'max',
 'redeemed',
 'lady',
 'ipod',
 'nyt',
 'supposed',
 'rental',
 'seen',
 'met',
 'ish',
 'figure',
 'via',
 'return',
 'swing',
 'laptop',
 'reveal',
 'semester',
 'bill',
 'direct',
 'sending',
 'askd',
 'shower',
 'load',
 'gotta',
 'complimentary',
 'correct',
 'red',
 'ac',
 'wow',
 'hospital',
 'confirm',
 'charged',
 'promise',
 'comp',
 'police',
 'gn',
 'slowly',
 'loved',
 'fact',
 'fantasy',
 'truth',
 'asap',
 'whenever',
 'idea',
 'laugh',
 'train',
 'door',
 'clean',
 'blood',
 'member',
 'rent',
 'monday',
 'remove',
 'asking',
 'slow',
 'discount',
 'hg',
 'ex',
 'small',
 'rest',
 'somebody',
 'hmv',
 'leaf',
 'wana',
 'own',
 'lover',
 'road',
 'bcoz',
 'study',
 'kate',
 'orchard',
 'bath',
 'muz',
 'safe',
 'wine',
 'lovable',
 'txting',
 'dogging',
 'entered',
 'page',
 'loan',
 'save',
 'rply',
 'checking',
 'joke',
 'crave',
 'abiola',
 'cheer',
 'comin',
 'eg',
 'link',
 'wap',
 'reward',
 'request',
 'usf',
 'std',
 'empty',
 'med',
 'hw',
 'doin',
 'cover',
 'write',
 'bb',
 'ringtones',
 'nobody',
 'energy',
 'doctor',
 'convey',
 'rd',
 'sale',
 'cr',
 'ntt',
 'otherwise',
 'poor',
 'gettin',
 'bag',
 'getzed',
 'summer',
 'wishing',
 'glad',
 'fantastic',
 'gap',
 'ho',
 'em',
 'cheap',
 'warm',
 'across',
 'hoping',
 'less',
 'opinion',
 'water',
 'different',
 'booked',
 'wc',
 'ldn',
 'voice',
 'yep',
 'mm',
 'mistake',
 'woke',
 'rakhesh',
 'custcare',
 'immediately',
 'pete',
 'merry',
 'normal',
 'somewhere',
 'tonite',
 'ge',
 'usual',
 'deep',
 'admirer',
 'kick',
 'teach',
 'deal',
 'bathe',
 'spend',
 'pray',
 'sony',
 'del',
 'men',
 'gave',
 'representative',
 'il',
 'short',
 'situation',
 'reached',
 'oops',
 'catch',
 'turn',
 'worried',
 'myself',
 'england',
 'copy',
 'callertune',
 'nah',
 'la',
 ...]

In [81]:
model.corpus_count

5569

In [82]:
model.epochs

5

In [84]:
model.wv.similar_by_word('good')

[('well', 0.9989132285118103),
 ('day', 0.9988243579864502),
 ('my', 0.9987761378288269),
 ('happy', 0.9987594485282898),
 ('great', 0.9987130165100098),
 ('dear', 0.9986855387687683),
 ('where', 0.9986844062805176),
 ('about', 0.9986671805381775),
 ('and', 0.9986621141433716),
 ('should', 0.9986061453819275)]

In [86]:
## using avg-word2vec

def avg_word2vec(doc):
    ##remove out of vocab words
    return np.mean([model.wv[word] for word in doc if word in model.wv.index_to_key])

In [87]:
%pip install tqdm

Requirement already satisfied: tqdm in c:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages (4.67.3)
Requirement already satisfied: colorama in c:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages (from tqdm) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
from tqdm import tqdm

In [89]:
#apply for the entire sentences
import numpy as np 
X = []
for i in tqdm(range(len(words))):
    X.append(avg_word2vec(words[i]))

  0%|          | 0/5569 [00:00<?, ?it/s]c:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\numpy\_core\fromnumeric.py:3824: RuntimeWarning: Mean of empty slice
  return _methods._mean(a, axis=axis, dtype=dtype,
c:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\numpy\_core\_methods.py:142: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
100%|██████████| 5569/5569 [00:00<00:00, 18280.45it/s]

In [90]:
X

[np.float32(0.0068381634),
 np.float32(0.0050836597),
 np.float32(0.007253772),
 np.float32(0.008557509),
 np.float32(0.007944235),
 np.float32(0.008508031),
 np.float32(0.008921214),
 np.float32(0.007435115),
 np.float32(0.0088160625),
 np.float32(0.009468399),
 np.float32(0.008394304),
 np.float32(0.008977853),
 np.float32(0.009901676),
 np.float32(0.009078236),
 np.float32(0.0089442115),
 np.float32(0.007504651),
 np.float32(0.008097453),
 np.float32(0.0064623533),
 np.float32(0.009618682),
 np.float32(0.0066531957),
 np.float32(0.009274002),
 np.float32(0.009175383),
 np.float32(0.006804182),
 np.float32(0.006770792),
 np.float32(0.009636275),
 np.float32(0.006292887),
 np.float32(0.0091618765),
 np.float32(0.009426633),
 np.float32(0.009829083),
 np.float32(0.008959806),
 np.float32(0.009861075),
 np.float32(0.009637067),
 np.float32(0.009717071),
 np.float32(0.010980922),
 np.float32(0.00894661),
 np.float32(0.008223233),
 np.float32(0.008099007),
 np.float32(0.009020499),
 np.float32(0.005638318),
 np.float32(0.009140091),
 np.float32(0.008355),
 np.float32(0.00995287),
 np.float32(0.009701612),
 np.float32(0.0107523175),
 np.float32(0.010299818),
 np.float32(0.008632395),
 np.float32(0.008537554),
 np.float32(0.008219946),
 np.float32(0.007119695),
 np.float32(0.0077978433),
 np.float32(0.009396235),
 np.float32(0.0088919625),
 np.float32(0.007943657),
 np.float32(0.0096954545),
 np.float32(0.0077412426),
 np.float32(0.010752652),
 np.float32(0.007735415),
 np.float32(0.008423498),
 np.float32(0.00854031),
 np.float32(0.010569752),
 np.float32(0.0091435695),
 np.float32(0.008724339),
 np.float32(0.006619376),
 np.float32(0.0077573056),
 np.float32(0.0060853767),
 np.float32(0.008896907),
 np.float32(0.008283346),
 np.float32(0.008593924),
 np.float32(0.010096608),
 np.float32(0.008946021),
 np.float32(0.005965317),
 np.float32(0.0094284685),
 np.float32(0.008746982),
 np.float32(0.012508124),
 np.float32(0.010387234),
 np.float32(0.009572496),
 np.float32(0.008414627),
 np.float32(0.009471008),
 np.float32(0.010825544),
 np.float32(0.0088374065),
 np.float32(0.009028647),
 np.float32(0.00985542),
 np.float32(0.009614543),
 np.float32(0.0103468755),
 np.float32(0.007330049),
 np.float32(0.009297176),
 np.float32(0.009063601),
 np.float32(0.008341987),
 np.float32(0.00928228),
 np.float32(0.0058557373),
 np.float32(0.0075846603),
 np.float32(0.009058578),
 np.float32(0.0077636996),
 np.float32(0.010081794),
 np.float32(0.007973087),
 np.float32(0.008994611),
 np.float32(0.0060244864),
 np.float32(0.008848202),
 np.float32(0.008619905),
 np.float32(0.008508873),
 np.float32(0.007204166),
 np.float32(0.008574685),
 np.float32(0.007435115),
 np.float32(0.007192595),
 np.float32(0.008635174),
 np.float32(0.008909251),
 np.float32(0.009150938),
 np.float32(0.0072565586),
 np.float32(0.008645485),
 np.float32(0.0066062436),
 np.float32(0.011184404),
 np.float32(0.009812758),
 np.float32(0.0081809545),
 np.float32(0.009921804),
 np.float32(0.0072056875),
 np.float32(0.007357261),
 np.float32(0.008550487),
 np.float32(0.00674957),
 np.float32(0.006667265),
 np.float32(0.0077896593),
 np.float32(0.009311225),
 np.float32(0.009756428),
 np.float32(0.007855224),
 np.float32(0.00937499),
 np.float32(0.0068273316),
 np.float32(0.010009594),
 np.float32(0.009178882),
 np.float32(0.0109936735),
 np.float32(0.008358891),
 np.float32(0.00871744),
 np.float32(0.009590039),
 np.float32(0.009855594),
 np.float32(0.0069417045),
 np.float32(0.0069578574),
 np.float32(0.0062778946),
 np.float32(0.007016147),
 np.float32(0.010222402),
 np.float32(0.008502514),
 np.float32(0.009117618),
 np.float32(0.0070335143),
 np.float32(0.010623618),
 np.float32(0.008418367),
 np.float32(0.006370662),
 np.float32(0.011220856),
 np.float32(0.009780412),
 np.float32(0.0074270926),
 np.float32(0.00821842),
 np.float32(0.0077659474),
 np.float32(0.010479581),
 np.float32(0.008338434),
 np.float32(0.009834487),
 np.float32(0.0072685475),
 np.float32(0.008761962),
 np.float32(0.007435115),
 np.float32(0.009759123),
 np.float32(0.012512953),
 np.float32(0.007258901),
 np.float32(0.011422382),
 np.float32(0.009344047),
 np.float32(0.008552231),
 np.float32(0.009469981),
 np.float32(0.008926119),
 np.float32(0.010185051),
 np.float32(0.008815653),
 np.float32(0.0075875083),
 np.float32(0.00942292),
 np.float32(0.010087647),
 np.float32(0.008462238),
 np.float32(0.00925031),
 np.float32(0.007508746),
 np.float32(0.006834494),
 np.float32(0.0071064113),
 np.float32(0.009567258),
 np.float32(0.0075486456),
 np.float32(0.0089967735),
 np.float32(0.009610866),
 np.float32(0.010906919),
 np.float32(0.009493186),
 np.float32(0.008870241),
 np.float32(0.009994853),
 np.float32(0.009275107),
 np.float32(0.007927198),
 np.float32(0.008881518),
 np.float32(0.008859362),
 np.float32(0.00758878),
 np.float32(0.008513576),
 np.float32(0.007508621),
 np.float32(0.009590371),
 np.float32(0.009789269),
 np.float32(0.006826344),
 np.float32(0.010234971),
 np.float32(0.009472201),
 np.float32(0.0064245034),
 np.float32(0.008653877),
 np.float32(0.010652404),
 np.float32(0.007681653),
 np.float32(0.008945113),
 np.float32(0.007907401),
 np.float32(0.009725361),
 np.float32(0.010878325),
 np.float32(0.010336743),
 np.float32(0.0070583187),
 np.float32(0.009537093),
 np.float32(0.0027848505),
 np.float32(0.009394067),
 np.float32(0.006296409),
 np.float32(0.007357261),
 np.float32(0.004565427),
 np.float32(0.0088449605),
 np.float32(0.0061054756),
 np.float32(0.009856774),
 np.float32(0.009428949),
 np.float32(0.008507934),
 np.float32(0.006543913),
 np.float32(0.0108798295),
 np.float32(0.0067086252),
 np.float32(0.006286144),
 np.float32(0.0069061364),
 np.float32(0.009088772),
 np.float32(0.009612534),
 np.float32(0.008635374),
 np.float32(0.008261212),
 np.float32(0.009028647),
 np.float32(0.006830267),
 np.float32(0.007999368),
 np.float32(0.0088778045),
 np.float32(0.007744006),
 np.float32(0.00654827),
 np.float32(0.0070644016),
 np.float32(0.010718804),
 np.float32(0.0075212247),
 np.float32(0.011821679),
 np.float32(0.0056370096),
 np.float32(0.007685454),
 np.float32(0.008009288),
 np.float32(0.011203359),
 np.float32(0.008588409),
 np.float32(0.010292878),
 np.float32(0.008120141),
 np.float32(0.008791561),
 np.float32(0.0073760133),
 np.float32(0.00623317),
 np.float32(0.009099169),
 np.float32(0.00700313),
 np.float32(0.008425317),
 np.float32(0.009906914),
 np.float32(0.009409361),
 np.float32(0.005480528),
 np.float32(0.009101004),
 np.float32(0.0072341207),
 np.float32(0.007417164),
 np.float32(0.00672831),
 np.float32(0.012475992),
 np.float32(0.009656629),
 np.float32(0.009016769),
 np.float32(0.009456481),
 np.float32(0.009525679),
 np.float32(0.01105138),
 np.float32(0.0086876135),
 np.float32(0.011150765),
 np.float32(0.004963968),
 np.float32(0.007478622),
 np.float32(0.009236642),
 np.float32(0.008511499),
 np.float32(0.009055391),
 np.float32(0.0053429697),
 np.float32(0.00847823),
 np.float32(0.007987662),
 np.float32(0.009245269),
 np.float32(0.008270098),
 np.float32(0.009070255),
 np.float32(0.008256754),
 np.float32(0.007602272),
 np.float32(0.0071429126),
 np.float32(0.0076233004),
 np.float32(0.003405656),
 np.float32(0.010168085),
 np.float32(0.008489739),
 np.float32(0.0092895795),
 np.float32(0.007663904),
 np.float32(0.009638383),
 np.float32(0.0063487687),
 np.float32(0.007382432),
 np.float32(0.002709725),
 np.float32(0.008911269),
 np.float32(0.008441367),
 np.float32(0.006573175),
 np.float32(0.008899894),
 np.float32(0.009061467),
 np.float32(0.007434122),
 np.float32(0.009432284),
 np.float32(0.0069210967),
 np.float32(0.0074188076),
 np.float32(0.012959273),
 np.float32(0.010264716),
 np.float32(0.008517404),
 np.float32(0.008070713),
 np.float32(0.008414081),
 np.float32(0.008596192),
 np.float32(0.008262183),
 np.float32(0.008097353),
 np.float32(0.008830021),
 np.float32(0.009956105),
 np.float32(0.008985119),
 np.float32(0.0069489386),
 np.float32(0.009005185),
 np.float32(0.007568414),
 np.float32(0.008436023),
 np.float32(0.008374069),
 np.float32(0.009209585),
 np.float32(0.0064871),
 np.float32(0.0088927895),
 np.float32(0.008959977),
 np.float32(0.00908242),
 np.float32(0.01096444),
 np.float32(0.0050052516),
 np.float32(0.006545659),
 np.float32(0.008989256),
 np.float32(0.00920519),
 np.float32(0.0036234597),
 np.float32(0.008388141),
 np.float32(0.008849846),
 np.float32(0.007244662),
 np.float32(0.009062366),
 np.float32(0.010579281),
 np.float32(0.008632395),
 np.float32(0.0093232),
 np.float32(0.008173141),
 np.float32(0.010044089),
 np.float32(0.008303998),
 np.float32(0.008802628),
 np.float32(0.00712557),
 np.float32(0.0073801065),
 np.float32(0.010109061),
 np.float32(0.008639196),
 np.float32(0.009922044),
 np.float32(0.009360043),
 np.float32(0.0066111158),
 np.float32(0.009028647),
 np.float32(0.008073524),
 np.float32(0.008230878),
 np.float32(0.0095617),
 np.float32(0.010019224),
 np.float32(0.009646402),
 np.float32(0.006096022),
 np.float32(0.0091633545),
 np.float32(0.0064593763),
 np.float32(0.006597426),
 np.float32(0.006988515),
 np.float32(0.009421112),
 np.float32(0.009249528),
 np.float32(0.009831085),
 np.float32(0.008010477),
 np.float32(0.008834136),
 np.float32(0.008096475),
 np.float32(0.008357449),
 np.float32(0.0072341207),
 np.float32(0.007648848),
 np.float32(0.00873994),
 np.float32(0.0077185375),
 np.float32(0.006255739),
 np.float32(0.0073671327),
 np.float32(0.007349094),
 np.float32(0.008086771),
 np.float32(0.010366585),
 np.float32(0.009649391),
 np.float32(0.0076284134),
 np.float32(0.009167017),
 np.float32(0.009590942),
 np.float32(0.009357057),
 np.float32(0.009113337),
 np.float32(0.009683873),
 np.float32(0.010412705),
 np.float32(0.009325439),
 np.float32(0.008254615),
 np.float32(0.00995153),
 np.float32(0.009859282),
 np.float32(0.008997037),
 np.float32(0.008982475),
 np.float32(0.008501471),
 np.float32(0.008434336),
 np.float32(0.0075957007),
 np.float32(0.008135923),
 np.float32(0.009153644),
 np.float32(0.007850409),
 np.float32(0.00422818),
 np.float32(0.009925409),
 np.float32(0.008789104),
 np.float32(0.00797423),
 np.float32(0.0080103325),
 np.float32(0.0057883635),
 np.float32(0.0097903125),
 np.float32(0.0099453125),
 np.float32(0.008998032),
 np.float32(0.009852209),
 np.float32(0.008551328),
 np.float32(0.00806824),
 np.float32(0.008646073),
 np.float32(0.008774801),
 np.float32(0.007822717),
 np.float32(0.009488394),
 np.float32(0.010217353),
 np.float32(0.009044821),
 np.float32(0.007794274),
 np.float32(0.009202987),
 np.float32(0.0078802025),
 np.float32(0.008487881),
 np.float32(0.008450463),
 np.float32(0.002068961),
 np.float32(0.0067282296),
 np.float32(0.009852248),
 np.float32(0.0101350965),
 np.float32(0.006878199),
 np.float32(0.008621127),
 np.float32(0.005880194),
 np.float32(0.009285612),
 np.float32(0.007738225),
 np.float32(0.008742717),
 np.float32(0.008677449),
 np.float32(0.006850695),
 np.float32(0.0079455795),
 np.float32(0.008866399),
 np.float32(0.0054509216),
 np.float32(0.009387746),
 np.float32(0.008780567),
 np.float32(0.007644532),
 np.float32(0.010261015),
 np.float32(0.008407004),
 np.float32(0.007934873),
 np.float32(0.007830927),
 np.float32(0.007426221),
 np.float32(0.0074990434),
 np.float32(0.007153123),
 np.float32(0.0051792907),
 np.float32(0.009778246),
 np.float32(0.010253583),
 np.float32(0.008278815),
 np.float32(0.0072232815),
 np.float32(0.009502735),
 np.float32(0.0105942385),
 np.float32(0.007968897),
 np.float32(0.00879229),
 np.float32(0.0065570474),
 np.float32(0.009028647),
 np.float32(0.010033428),
 np.float32(0.009077736),
 np.float32(0.0065737735),
 np.float32(0.010322301),
 np.float32(0.009616318),
 np.float32(0.010020039),
 np.float64(nan),
 np.float32(0.01122767),
 np.float32(0.009347025),
 np.float32(0.009211378),
 np.float32(0.009772794),
 np.float32(0.0067063235),
 np.float32(0.009039407),
 np.float32(0.0085890945),
 np.float32(0.007907794),
 np.float32(0.007736334),
 np.float32(0.009604821),
 np.float32(0.0081722755),
 np.float32(0.008527384),
 np.float32(0.007302823),
 np.float32(0.009765283),
 np.float32(0.009299922),
 np.float32(0.009425262),
 np.float32(0.01096149),
 np.float32(0.0070878374),
 np.float32(0.0092564775),
 np.float32(0.008428931),
 np.float32(0.008613055),
 np.float32(0.008649609),
 np.float32(0.0062461323),
 np.float32(0.008156617),
 np.float32(0.0076056444),
 np.float32(0.008924417),
 np.float32(0.007609933),
 np.float32(0.009115319),
 np.float32(0.009260562),
 np.float32(0.0066645513),
 np.float32(0.008992853),
 np.float32(0.0054464466),
 np.float32(0.008550069),
 np.float32(0.008524043),
 np.float32(0.008949441),
 np.float32(0.008644849),
 np.float32(0.008965476),
 np.float32(0.00844793),
 np.float32(0.008540083),
 np.float32(0.0091226185),
 np.float32(0.007735415),
 np.float32(0.008423499),
 np.float32(0.010969299),
 np.float32(0.01165993),
 np.float32(0.007038385),
 np.float32(0.0074342974),
 np.float32(0.008433529),
 np.float32(0.004886),
 np.float32(0.009870479),
 np.float32(0.008188957),
 np.float32(0.010540173),
 np.float32(0.008590535),
 np.float32(0.008258491),
 np.float32(0.009391161),
 np.float32(0.008321792),
 np.float32(0.006747781),
 np.float32(0.009472407),
 np.float32(0.011652028),
 np.float32(0.006340437),
 np.float32(0.01066496),
 np.float32(0.0043632532),
 np.float32(0.009149988),
 np.float32(0.0057184193),
 np.float32(0.008387916),
 np.float32(0.008081878),
 np.float32(0.008858498),
 np.float32(0.009290565),
 np.float32(0.009097752),
 np.float32(0.008534873),
 np.float32(0.008569782),
 np.float32(0.008605021),
 np.float32(0.009059313),
 np.float32(0.0100604175),
 np.float32(0.009435274),
 np.float32(0.0066922726),
 np.float32(0.00750261),
 np.float32(0.0074202134),
 np.float32(0.008918532),
 np.float32(0.00901165),
 np.float32(0.006937647),
 np.float32(0.008743233),
 np.float32(0.0091633545),
 np.float32(0.008100751),
 np.float32(0.009494735),
 np.float32(0.009262913),
 np.float32(0.009874862),
 np.float32(0.008306896),
 np.float32(0.008674981),
 np.float32(0.008928911),
 np.float32(0.008818472),
 np.float32(0.008941672),
 np.float32(0.008746239),
 np.float32(0.007631701),
 np.float32(0.0072610807),
 np.float32(0.009164816),
 np.float32(0.009734914),
 np.float32(0.0072424603),
 np.float32(0.011446621),
 np.float32(0.008983076),
 np.float32(0.008810457),
 np.float32(0.008078328),
 np.float32(0.010197706),
 np.float32(0.009164847),
 np.float32(0.008514422),
 np.float32(0.008430295),
 np.float32(0.009800008),
 np.float32(0.010325215),
 np.float32(0.010371703),
 np.float32(0.0070725405),
 np.float32(0.008410496),
 np.float32(0.0064043514),
 np.float32(0.008564411),
 np.float32(0.009921804),
 np.float32(0.009716083),
 np.float32(0.0075979717),
 np.float32(0.010135385),
 np.float32(0.00997848),
 np.float32(0.00878454),
 np.float32(0.007611914),
 np.float32(0.006936697),
 np.float32(0.010792221),
 np.float32(0.008377074),
 np.float32(0.010461095),
 np.float32(0.0047086487),
 np.float32(0.012090747),
 np.float32(0.010684105),
 np.float32(0.0065400153),
 np.float32(0.010125391),
 np.float32(0.008134094),
 np.float32(0.00565303),
 np.float32(0.009331948),
 np.float32(0.010009036),
 np.float32(0.008813683),
 np.float32(0.009776619),
 np.float32(0.009124154),
 np.float32(0.0073518697),
 np.float32(0.007568263),
 np.float32(0.006024635),
 np.float32(0.009003586),
 np.float32(0.007840046),
 np.float32(0.008256281),
 np.float32(0.006937647),
 np.float32(0.011690068),
 np.float32(0.008214889),
 np.float32(0.01229826),
 np.float32(0.008857452),
 np.float32(0.008472923),
 np.float32(0.009619315),
 np.float32(0.0068104323),
 np.float32(0.007978227),
 np.float32(0.007483054),
 np.float32(0.00980008),
 np.float32(0.008424034),
 np.float32(0.0067002517),
 np.float32(0.009649541),
 np.float32(0.007235774),
 np.float32(0.008864599),
 np.float32(0.006015865),
 np.float32(0.008378809),
 np.float32(0.008365926),
 np.float32(0.008139619),
 np.float32(0.0101854345),
 np.float32(0.008657989),
 np.float32(0.009080053),
 np.float32(0.009155472),
 np.float32(0.007597914),
 np.float32(0.007523736),
 np.float32(0.007375137),
 np.float32(0.0071431766),
 np.float32(0.009896412),
 np.float32(0.008048557),
 np.float32(0.008101233),
 np.float32(0.008957359),
 np.float32(0.0079512745),
 np.float32(0.0094691105),
 np.float32(0.009299344),
 np.float32(0.007435081),
 np.float32(0.008608865),
 np.float32(0.008608653),
 np.float32(0.009872632),
 np.float32(0.0046653794),
 np.float32(0.009512805),
 np.float32(0.00861098),
 np.float32(0.009069267),
 np.float32(0.0076650833),
 np.float32(0.009899632),
 np.float32(0.0076431083),
 np.float32(0.00923342),
 np.float32(0.007269941),
 np.float32(0.0088105),
 np.float32(0.00862805),
 np.float32(0.0070868516),
 np.float32(0.0071715135),
 np.float32(0.010079393),
 np.float32(0.007970187),
 np.float32(0.009937486),
 np.float32(0.006937647),
 np.float32(0.0082715815),
 np.float32(0.011539468),
 np.float32(0.0053380453),
 np.float32(0.008503607),
 np.float32(0.008282692),
 np.float32(0.009611257),
 np.float32(0.008945113),
 np.float32(0.0075681517),
 np.float32(0.008030511),
 np.float32(0.0103468755),
 np.float32(0.008969032),
 np.float32(0.011596657),
 np.float32(0.0076652956),
 np.float32(0.0074847843),
 np.float32(0.0072920714),
 np.float32(0.007825174),
 np.float32(0.009338327),
 np.float32(0.0058752093),
 np.float32(0.009141573),
 np.float32(0.009693222),
 np.float32(0.008027693),
 np.float32(0.0098478515),
 np.float32(0.004781426),
 np.float32(0.0063885227),
 np.float32(0.009048164),
 np.float32(0.009847966),
 np.float32(0.009759882),
 np.float32(0.0068958756),
 np.float32(0.00939623),
 np.float32(0.0074677295),
 np.float32(0.007099651),
 np.float32(0.008922492),
 np.float32(0.010249694),
 np.float32(0.007611339),
 np.float32(0.007101068),
 np.float32(0.008883556),
 np.float32(0.007712825),
 np.float32(0.009542923),
 np.float32(0.007617525),
 np.float32(0.008684929),
 np.float32(0.0077965534),
 np.float32(0.0089888815),
 np.float32(0.008805608),
 np.float32(0.007579987),
 np.float32(0.008388926),
 np.float32(0.009514604),
 np.float32(0.0076011466),
 np.float32(0.010513732),
 np.float32(0.008443064),
 np.float32(0.008763906),
 np.float32(0.007326854),
 np.float32(0.009962726),
 np.float32(0.007860362),
 np.float32(0.009028647),
 np.float32(0.009142788),
 np.float32(0.008021594),
 np.float32(0.008552254),
 np.float32(0.008770512),
 np.float32(0.008852339),
 np.float32(0.0043329503),
 np.float32(0.008416379),
 np.float32(0.00797423),
 np.float32(0.007161422),
 np.float32(0.009070964),
 np.float32(0.00813202),
 np.float32(0.008923882),
 np.float32(0.008226735),
 np.float32(0.009217268),
 np.float32(0.008032163),
 np.float32(0.009561937),
 np.float32(0.01008721),
 np.float32(0.008441083),
 np.float32(0.008459651),
 np.float32(0.008607607),
 np.float32(0.008841371),
 np.float32(0.009310112),
 np.float32(0.008882023),
 np.float32(0.0086526135),
 np.float32(0.008473107),
 np.float32(0.0056712804),
 np.float32(0.007926673),
 np.float32(0.007746962),
 np.float32(0.006540441),
 np.float32(0.0068836156),
 np.float32(0.009762998),
 np.float32(0.008055142),
 np.float32(0.0070832116),
 np.float32(0.008740917),
 np.float32(0.008223662),
 np.float32(0.008222779),
 np.float32(0.010782566),
 np.float32(0.007863148),
 np.float32(0.008241002),
 np.float32(0.00942121),
 np.float32(0.009031246),
 np.float32(0.0074507575),
 np.float32(0.006218297),
 np.float32(0.007982013),
 np.float32(0.009112966),
 np.float32(0.0100804195),
 np.float32(0.009764362),
 np.float32(0.008450284),
 np.float32(0.0092837345),
 np.float32(0.009477917),
 np.float32(0.01090784),
 np.float32(0.00999285),
 np.float32(0.009409321),
 np.float32(0.007619355),
 np.float32(0.008152383),
 np.float32(0.008233468),
 np.float32(0.0074156527),
 np.float32(0.009791181),
 np.float32(0.007377639),
 np.float32(0.009309328),
 np.float32(0.009045345),
 np.float32(0.0077743623),
 np.float32(0.008075418),
 np.float32(0.0067532067),

In [92]:
len(X)

5569

In [ ]:
X_new = np.array(X) #independent features

In [94]:
#dependent feature 
y = pd.get_dummies(['label'])
y = y.iloc[:,0].values